[platformio]
description = PS4 slopkit esp32

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

upload_speed = 921600
monitor_speed = 115200

build_flags =
    -D CORE_DEBUG_LEVEL=3
    ;ESP_LOG_NONE,       0
    ;ESP_LOG_ERROR,      1
    ;ESP_LOG_WARN,       2
    ;ESP_LOG_INFO,       3
    ;ESP_LOG_DEBUG,      4
    ;ESP_LOG_VERBOSE     5

board_build.filesystem = littlefs
board_build.partitions = partitions.csv

[env:esp32-s2-mini]
platform = espressif32
board = lolin_s2_mini
framework = arduino

upload_speed = 921600
monitor_speed = 115200

build_flags =
    -D CORE_DEBUG_LEVEL=3
    -D ARDUINO_USB_CDC_ON_BOOT=1

board_build.filesystem = littlefs
board_build.partitions = partitions.csv
